[2025-10-24T00:25:16.995+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:25:16.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:25:16.997+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:25:16.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:25:17.608+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:25:17.607+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:25:17.608+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:25:17.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.624 seconds
[2025-10-24T00:25:47.863+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:25:47.864+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:25:47.865+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:25:47.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:25:48.122+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:25:48.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:25:48.122+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:25:48.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.270 seconds
[2025-10-24T00:26:18.351+0000] {processor.py:153} INFO - Started process (PID=155) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:26:18.352+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:26:18.352+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:26:18.352+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:26:18.594+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:26:18.593+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:26:18.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:26:18.600+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.251 seconds
[2025-10-24T00:26:48.644+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:26:48.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:26:48.646+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:26:48.646+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:26:49.004+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:26:49.002+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:26:49.004+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:26:49.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.373 seconds
[2025-10-24T00:27:19.070+0000] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:27:19.071+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:27:19.072+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:27:19.072+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:27:19.279+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:27:19.279+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:27:19.280+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:27:19.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.220 seconds
[2025-10-24T00:27:49.507+0000] {processor.py:153} INFO - Started process (PID=332) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:27:49.508+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:27:49.508+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:27:49.508+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:27:49.728+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:27:49.727+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:27:49.728+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:27:49.734+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.230 seconds
[2025-10-24T00:28:19.805+0000] {processor.py:153} INFO - Started process (PID=394) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:28:19.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:28:19.817+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:28:19.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:28:20.071+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:28:20.070+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:28:20.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:28:20.077+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.274 seconds
[2025-10-24T00:28:50.261+0000] {processor.py:153} INFO - Started process (PID=436) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:28:50.262+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:28:50.263+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:28:50.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:28:50.495+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:28:50.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:28:50.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:28:50.501+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.244 seconds
[2025-10-24T00:29:20.593+0000] {processor.py:153} INFO - Started process (PID=498) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:29:20.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:29:20.595+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:29:20.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:29:20.805+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:29:20.804+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:29:20.805+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:29:20.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.223 seconds
[2025-10-24T00:29:51.064+0000] {processor.py:153} INFO - Started process (PID=560) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:29:51.065+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:29:51.066+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:29:51.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:29:51.263+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:29:51.262+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:29:51.263+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:29:51.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.208 seconds
[2025-10-24T00:30:21.319+0000] {processor.py:153} INFO - Started process (PID=622) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:30:21.319+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:30:21.320+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:30:21.320+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:30:21.520+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:30:21.519+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:30:21.520+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:30:21.526+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.209 seconds
[2025-10-24T00:30:51.703+0000] {processor.py:153} INFO - Started process (PID=664) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:30:51.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:30:51.705+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:30:51.704+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:30:51.916+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:30:51.915+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:30:51.916+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:30:51.922+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.223 seconds
[2025-10-24T00:31:21.995+0000] {processor.py:153} INFO - Started process (PID=727) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:31:21.997+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:31:21.997+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:31:21.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:31:22.196+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:31:22.196+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:31:22.197+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:31:22.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.212 seconds
[2025-10-24T00:31:52.321+0000] {processor.py:153} INFO - Started process (PID=789) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:31:52.322+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:31:52.323+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:31:52.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:31:52.544+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:31:52.543+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:31:52.544+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:31:52.550+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.234 seconds
[2025-10-24T00:32:22.655+0000] {processor.py:153} INFO - Started process (PID=851) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:32:22.655+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:32:22.656+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:32:22.656+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:32:22.867+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:32:22.866+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:32:22.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:32:22.873+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.220 seconds
[2025-10-24T00:32:53.033+0000] {processor.py:153} INFO - Started process (PID=893) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:32:53.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:32:53.034+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:32:53.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:32:53.238+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:32:53.237+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:32:53.238+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:32:53.244+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.216 seconds
[2025-10-24T00:33:23.399+0000] {processor.py:153} INFO - Started process (PID=955) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:33:23.400+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:33:23.401+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:33:23.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:33:23.606+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:33:23.605+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:33:23.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:33:23.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.216 seconds
[2025-10-24T00:33:53.723+0000] {processor.py:153} INFO - Started process (PID=1017) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:33:53.724+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:33:53.724+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:33:53.724+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:33:53.926+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:33:53.925+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:33:53.926+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:33:53.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.213 seconds
[2025-10-24T00:34:24.154+0000] {processor.py:153} INFO - Started process (PID=1079) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:34:24.155+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:34:24.156+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:34:24.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:34:24.371+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:34:24.370+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:34:24.371+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:34:24.377+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.227 seconds
[2025-10-24T00:34:54.484+0000] {processor.py:153} INFO - Started process (PID=1121) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:34:54.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:34:54.486+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:34:54.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:34:54.769+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:34:54.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:34:54.769+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:34:54.776+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.298 seconds
[2025-10-24T00:35:25.035+0000] {processor.py:153} INFO - Started process (PID=1183) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:35:25.036+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:35:25.037+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:35:25.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:35:25.272+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:35:25.271+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:35:25.272+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:35:25.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.248 seconds
[2025-10-24T00:35:55.362+0000] {processor.py:153} INFO - Started process (PID=1245) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:35:55.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:35:55.363+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:35:55.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:35:55.591+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:35:55.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:35:55.591+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:35:55.597+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.238 seconds
[2025-10-24T00:36:25.862+0000] {processor.py:153} INFO - Started process (PID=1307) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:36:25.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:36:25.862+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:36:25.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:36:26.056+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:36:26.055+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:36:26.056+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:36:26.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.204 seconds
[2025-10-24T00:36:56.152+0000] {processor.py:153} INFO - Started process (PID=1349) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:36:56.153+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:36:56.153+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:36:56.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:36:56.364+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:36:56.363+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:36:56.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:36:56.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.223 seconds
[2025-10-24T00:37:26.618+0000] {processor.py:153} INFO - Started process (PID=1411) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:37:26.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:37:26.619+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:37:26.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:37:26.836+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:37:26.836+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:37:26.837+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:37:26.843+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.229 seconds
[2025-10-24T00:37:56.889+0000] {processor.py:153} INFO - Started process (PID=1472) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:37:56.889+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:37:56.890+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:37:56.890+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:37:57.107+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:37:57.106+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:37:57.107+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:37:57.113+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.228 seconds
[2025-10-24T00:38:27.399+0000] {processor.py:153} INFO - Started process (PID=1534) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:38:27.399+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:38:27.399+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:38:27.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:38:27.653+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:38:27.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:38:27.653+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:38:27.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.262 seconds
[2025-10-24T00:38:57.996+0000] {processor.py:153} INFO - Started process (PID=1576) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:38:57.996+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:38:57.997+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:38:57.997+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:38:58.223+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:38:58.222+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:38:58.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:38:58.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.235 seconds
[2025-10-24T00:39:28.311+0000] {processor.py:153} INFO - Started process (PID=1638) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:39:28.313+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:39:28.314+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:39:28.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:39:28.517+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:39:28.516+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:39:28.518+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:39:28.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.218 seconds
[2025-10-24T00:39:58.815+0000] {processor.py:153} INFO - Started process (PID=1700) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:39:58.816+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:39:58.817+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:39:58.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:39:59.045+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:39:59.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:39:59.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:39:59.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.241 seconds
[2025-10-24T00:40:29.092+0000] {processor.py:153} INFO - Started process (PID=1762) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:40:29.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:40:29.094+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:40:29.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:40:29.371+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:40:29.370+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:40:29.372+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:40:29.378+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.290 seconds
[2025-10-24T00:40:59.541+0000] {processor.py:153} INFO - Started process (PID=1804) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:40:59.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:40:59.543+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:40:59.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:40:59.755+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:40:59.754+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:40:59.755+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:40:59.761+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.224 seconds
[2025-10-24T00:41:29.895+0000] {processor.py:153} INFO - Started process (PID=1866) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:41:29.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:41:29.897+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:41:29.897+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:41:30.140+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:41:30.139+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:41:30.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:41:30.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.254 seconds
[2025-10-24T00:42:00.301+0000] {processor.py:153} INFO - Started process (PID=1928) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:42:00.302+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:42:00.302+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:42:00.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:42:00.564+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:42:00.563+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:42:00.564+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:42:00.571+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.275 seconds
[2025-10-24T00:42:30.619+0000] {processor.py:153} INFO - Started process (PID=1990) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:42:30.620+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:42:30.621+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:42:30.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:42:30.823+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:42:30.822+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:42:30.823+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:42:30.829+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.214 seconds
[2025-10-24T00:43:00.996+0000] {processor.py:153} INFO - Started process (PID=2032) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:43:00.997+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:43:00.998+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:43:00.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:43:01.208+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:43:01.207+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:43:01.209+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:43:01.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.223 seconds
[2025-10-24T00:43:31.293+0000] {processor.py:153} INFO - Started process (PID=2094) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:43:31.294+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:43:31.295+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:43:31.295+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:43:31.500+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:43:31.499+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:43:31.500+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:43:31.506+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.218 seconds
[2025-10-24T00:44:01.659+0000] {processor.py:153} INFO - Started process (PID=2156) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:44:01.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:44:01.660+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:44:01.660+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:44:01.894+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:44:01.892+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:44:01.894+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:44:01.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.250 seconds
[2025-10-24T00:44:32.033+0000] {processor.py:153} INFO - Started process (PID=2218) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:44:32.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:44:32.035+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:44:32.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:44:32.233+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:44:32.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:44:32.234+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:44:32.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.210 seconds
[2025-10-24T00:45:02.453+0000] {processor.py:153} INFO - Started process (PID=2260) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:45:02.454+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:45:02.455+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:45:02.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:45:02.666+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:45:02.666+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:45:02.667+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:45:02.673+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.224 seconds
[2025-10-24T00:45:32.774+0000] {processor.py:153} INFO - Started process (PID=2322) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:45:32.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:45:32.776+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:45:32.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:45:33.016+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:45:33.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:45:33.016+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:45:33.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.255 seconds
[2025-10-24T00:46:03.176+0000] {processor.py:153} INFO - Started process (PID=2384) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:46:03.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:46:03.178+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:46:03.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:46:03.381+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:46:03.380+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 12, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:46:03.381+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:46:03.387+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.215 seconds
[2025-10-24T00:49:50.660+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:49:50.660+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:49:50.661+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:49:50.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:49:51.260+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:49:51.259+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 30, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:49:51.260+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:49:51.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.625 seconds
[2025-10-24T00:50:21.549+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:50:21.549+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:50:21.550+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:50:21.550+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:50:21.826+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:50:21.825+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 30, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:50:21.826+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:50:21.832+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.289 seconds
[2025-10-24T00:50:52.107+0000] {processor.py:153} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:50:52.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:50:52.108+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:50:52.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:50:52.398+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:50:52.397+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
  File "/opt/airflow/dags/../scripts/datapipeline.py", line 2, in <module>
    from data_collection import collect_bluebikes_data, collect_boston_college_data, collect_NOAA_Weather_data
  File "/opt/airflow/dags/../scripts/data_collection.py", line 30, in <module>
    def collect_bluebikes_data(index_url: str, years: list[str], download_dir: str, parquet_dir: str, log_path: str):
TypeError: 'type' object is not subscriptable
[2025-10-24T00:50:52.399+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:50:52.407+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.302 seconds
[2025-10-24T00:51:49.125+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:51:49.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:51:49.128+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:51:49.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:51:49.753+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:51:49.753+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:51:49.754+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:51:49.762+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.639 seconds
[2025-10-24T00:52:20.013+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:52:20.014+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:52:20.015+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:52:20.015+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:52:20.292+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:52:20.291+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:52:20.292+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:52:20.298+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.289 seconds
[2025-10-24T00:52:50.564+0000] {processor.py:153} INFO - Started process (PID=166) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:52:50.565+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:52:50.566+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:52:50.566+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:52:50.831+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:52:50.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:52:50.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:52:50.840+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.278 seconds
[2025-10-24T00:53:21.050+0000] {processor.py:153} INFO - Started process (PID=208) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:53:21.051+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:53:21.052+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:53:21.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:53:21.261+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:53:21.261+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:53:21.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:53:21.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.222 seconds
[2025-10-24T00:53:51.361+0000] {processor.py:153} INFO - Started process (PID=269) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:53:51.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:53:51.364+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:53:51.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:53:51.643+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:53:51.642+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:53:51.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:53:51.649+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.292 seconds
[2025-10-24T00:54:21.774+0000] {processor.py:153} INFO - Started process (PID=331) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:54:21.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:54:21.776+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:54:21.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:54:22.029+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:54:22.028+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:54:22.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:54:22.036+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.265 seconds
[2025-10-24T00:54:52.097+0000] {processor.py:153} INFO - Started process (PID=373) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:54:52.098+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:54:52.099+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:54:52.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:54:52.368+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:54:52.367+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:54:52.368+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:54:52.374+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.281 seconds
[2025-10-24T00:55:22.503+0000] {processor.py:153} INFO - Started process (PID=435) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:22.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:55:22.504+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:55:22.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:22.745+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:55:22.744+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_bluebikes' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:55:22.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:22.759+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.257 seconds
[2025-10-24T00:55:25.593+0000] {processor.py:153} INFO - Started process (PID=446) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:25.593+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:55:25.593+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:55:25.593+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:25.813+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:55:25.813+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_boston_colleges_data' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:55:25.814+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:25.838+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.247 seconds
[2025-10-24T00:55:56.061+0000] {processor.py:153} INFO - Started process (PID=499) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:56.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:55:56.063+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:55:56.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:56.363+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:55:56.362+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 8, in <module>
    from datapipeline import (
ImportError: cannot import name 'collect_boston_colleges_data' from 'datapipeline' (/opt/airflow/dags/../scripts/datapipeline.py)
[2025-10-24T00:55:56.363+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:55:56.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.311 seconds
[2025-10-24T00:56:24.384+0000] {processor.py:153} INFO - Started process (PID=561) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:56:24.386+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:56:24.387+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:56:24.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:56:24.678+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:56:24.677+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 86, in <module>
    [t1, t2, t3] >> processing_tasks
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2025-10-24T00:56:24.678+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:56:24.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.310 seconds
[2025-10-24T00:56:55.376+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:56:55.377+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:56:55.378+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:56:55.378+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:56:56.077+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:56:56.076+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 86, in <module>
    [t1, t2, t3] >> processing_tasks
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2025-10-24T00:56:56.077+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:56:56.089+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.719 seconds
[2025-10-24T00:57:26.357+0000] {processor.py:153} INFO - Started process (PID=104) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:57:26.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:57:26.360+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:26.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:57:26.664+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:26.663+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/data_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/data_pipeline_dag.py", line 86, in <module>
    [t1, t2, t3] >> processing_tasks
TypeError: unsupported operand type(s) for >>: 'list' and 'list'
[2025-10-24T00:57:26.664+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:57:26.673+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.321 seconds
[2025-10-24T00:57:54.841+0000] {processor.py:153} INFO - Started process (PID=146) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:57:54.843+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:57:54.844+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:54.844+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:57:55.286+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:57:55.370+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:55.370+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:data_pipeline_dag
[2025-10-24T00:57:55.373+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:55.373+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:data_pipeline_dag
[2025-10-24T00:57:55.375+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:55.375+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:data_pipeline_dag
[2025-10-24T00:57:55.376+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:55.375+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T00:57:55.381+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:55.381+0000] {dag.py:2711} INFO - Creating ORM DAG for data_pipeline_dag
[2025-10-24T00:57:55.386+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:57:55.385+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-23T00:00:00+00:00, run_after=2025-10-24T00:00:00+00:00
[2025-10-24T00:57:55.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.556 seconds
[2025-10-24T00:58:26.537+0000] {processor.py:153} INFO - Started process (PID=41) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:58:26.538+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:58:26.539+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:58:26.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:58:27.236+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:58:27.249+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:58:27.249+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T00:58:27.261+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:58:27.261+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-23T00:00:00+00:00, run_after=2025-10-24T00:00:00+00:00
[2025-10-24T00:58:27.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.734 seconds
[2025-10-24T00:58:57.528+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:58:57.529+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:58:57.529+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:58:57.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:58:57.798+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:58:57.807+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:58:57.807+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T00:58:57.816+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:58:57.816+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-23T00:00:00+00:00, run_after=2025-10-24T00:00:00+00:00
[2025-10-24T00:58:57.822+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.298 seconds
[2025-10-24T00:59:28.007+0000] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:59:28.007+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:59:28.007+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:59:28.007+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:59:28.265+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:59:28.275+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:59:28.275+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T00:59:28.287+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:59:28.287+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T00:59:28.296+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.291 seconds
[2025-10-24T00:59:58.579+0000] {processor.py:153} INFO - Started process (PID=212) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:59:58.580+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T00:59:58.581+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:59:58.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:59:58.893+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T00:59:58.904+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:59:58.904+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T00:59:58.914+0000] {logging_mixin.py:137} INFO - [2025-10-24T00:59:58.914+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T00:59:58.920+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.346 seconds
[2025-10-24T01:00:29.173+0000] {processor.py:153} INFO - Started process (PID=274) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:00:29.174+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:00:29.176+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:00:29.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:00:29.424+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:00:29.432+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:00:29.432+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:00:29.441+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:00:29.441+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:00:29.447+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.279 seconds
[2025-10-24T01:00:59.707+0000] {processor.py:153} INFO - Started process (PID=336) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:00:59.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:00:59.709+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:00:59.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:00:59.931+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:00:59.940+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:00:59.940+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:00:59.949+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:00:59.949+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:00:59.956+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.253 seconds
[2025-10-24T01:01:30.128+0000] {processor.py:153} INFO - Started process (PID=398) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:01:30.128+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:01:30.129+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:01:30.129+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:01:30.375+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:01:30.384+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:01:30.384+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:01:30.394+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:01:30.394+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:01:30.400+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.275 seconds
[2025-10-24T01:02:00.672+0000] {processor.py:153} INFO - Started process (PID=440) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:00.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:02:00.675+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:00.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:01.013+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:01.029+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:01.029+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:02:01.040+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:01.040+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:02:01.047+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.379 seconds
[2025-10-24T01:02:17.166+0000] {processor.py:153} INFO - Started process (PID=482) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:17.167+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:02:17.168+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:17.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:17.388+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:17.410+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:17.410+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:02:17.419+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:17.419+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:02:17.427+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.263 seconds
[2025-10-24T01:02:52.725+0000] {processor.py:153} INFO - Started process (PID=42) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:52.726+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:02:52.726+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:52.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:53.387+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:02:53.399+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:53.398+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:02:53.412+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:02:53.412+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:02:53.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.697 seconds
[2025-10-24T01:03:23.644+0000] {processor.py:153} INFO - Started process (PID=108) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:03:23.645+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:03:23.645+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:03:23.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:03:23.898+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:03:23.908+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:03:23.908+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:03:23.918+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:03:23.918+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:03:23.925+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.282 seconds
[2025-10-24T01:03:54.155+0000] {processor.py:153} INFO - Started process (PID=169) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:03:54.156+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:03:54.156+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:03:54.156+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:03:54.601+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:03:54.617+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:03:54.616+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:03:54.633+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:03:54.633+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:03:54.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.490 seconds
[2025-10-24T01:04:24.858+0000] {processor.py:153} INFO - Started process (PID=211) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:04:24.859+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:04:24.859+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:04:24.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:04:25.283+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:04:25.295+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:04:25.295+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:04:25.308+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:04:25.308+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:04:25.315+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.460 seconds
[2025-10-24T01:04:55.548+0000] {processor.py:153} INFO - Started process (PID=273) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:04:55.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:04:55.551+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:04:55.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:04:55.880+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:04:55.893+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:04:55.892+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:04:55.913+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:04:55.913+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:04:55.924+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.384 seconds
[2025-10-24T01:05:26.146+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:05:26.147+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:05:26.147+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:05:26.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:05:26.460+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:05:26.473+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:05:26.473+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:05:26.484+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:05:26.484+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:05:26.493+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.350 seconds
[2025-10-24T01:05:56.735+0000] {processor.py:153} INFO - Started process (PID=383) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:05:56.736+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:05:56.737+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:05:56.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:05:57.083+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:05:57.093+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:05:57.093+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:05:57.103+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:05:57.103+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:05:57.110+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.382 seconds
[2025-10-24T01:06:27.445+0000] {processor.py:153} INFO - Started process (PID=445) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:06:27.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:06:27.449+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:06:27.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:06:27.924+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:06:27.949+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:06:27.949+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:06:27.966+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:06:27.966+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:06:27.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.541 seconds
[2025-10-24T01:06:58.198+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:06:58.199+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:06:58.200+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:06:58.200+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:06:58.517+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:06:58.527+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:06:58.527+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:06:58.538+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:06:58.538+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:06:58.545+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.352 seconds
[2025-10-24T01:07:18.391+0000] {processor.py:153} INFO - Started process (PID=549) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:07:18.394+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:07:18.397+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:07:18.397+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:07:18.801+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:07:18.831+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:07:18.831+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:07:18.841+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:07:18.841+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:07:18.850+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.480 seconds
[2025-10-24T01:07:48.986+0000] {processor.py:153} INFO - Started process (PID=591) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:07:48.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:07:48.987+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:07:48.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:07:49.240+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:07:49.249+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:07:49.249+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:07:49.257+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:07:49.257+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:07:49.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.281 seconds
[2025-10-24T01:08:19.341+0000] {processor.py:153} INFO - Started process (PID=653) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:08:19.341+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:08:19.342+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:08:19.342+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:08:19.586+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:08:19.594+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:08:19.594+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:08:19.604+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:08:19.603+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:08:19.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.271 seconds
[2025-10-24T01:08:49.726+0000] {processor.py:153} INFO - Started process (PID=715) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:08:49.728+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:08:49.728+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:08:49.728+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:08:50.041+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:08:50.051+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:08:50.050+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:08:50.061+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:08:50.061+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:08:50.068+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.344 seconds
[2025-10-24T01:09:05.344+0000] {processor.py:153} INFO - Started process (PID=41) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:09:05.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:09:05.346+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:09:05.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:09:06.044+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:09:06.055+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:09:06.055+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:09:06.071+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:09:06.070+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:09:06.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.737 seconds
[2025-10-24T01:09:36.312+0000] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:09:36.313+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:09:36.313+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:09:36.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:09:36.567+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:09:36.578+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:09:36.578+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:09:36.588+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:09:36.588+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:09:36.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.284 seconds
[2025-10-24T01:10:06.805+0000] {processor.py:153} INFO - Started process (PID=170) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:10:06.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:10:06.811+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:10:06.810+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:10:07.261+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:10:07.275+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:10:07.274+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:10:07.293+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:10:07.293+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:10:07.303+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.518 seconds
[2025-10-24T01:10:37.572+0000] {processor.py:153} INFO - Started process (PID=212) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:10:37.574+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:10:37.575+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:10:37.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:10:37.860+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:10:37.869+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:10:37.868+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:10:37.878+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:10:37.878+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:10:37.885+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.317 seconds
[2025-10-24T01:11:08.074+0000] {processor.py:153} INFO - Started process (PID=274) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:11:08.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:11:08.076+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:11:08.076+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:11:08.455+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:11:08.465+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:11:08.465+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:11:08.475+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:11:08.475+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:11:08.481+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.411 seconds
[2025-10-24T01:11:38.662+0000] {processor.py:153} INFO - Started process (PID=337) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:11:38.664+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:11:38.665+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:11:38.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:11:38.975+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:11:38.984+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:11:38.984+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:11:38.993+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:11:38.993+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:11:38.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.342 seconds
[2025-10-24T01:12:09.233+0000] {processor.py:153} INFO - Started process (PID=388) to work on /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:12:09.234+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/data_pipeline_dag.py for tasks to queue
[2025-10-24T01:12:09.234+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:12:09.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:12:09.684+0000] {processor.py:753} INFO - DAG(s) dict_keys(['data_pipeline_dag']) retrieved from /opt/airflow/dags/data_pipeline_dag.py
[2025-10-24T01:12:09.701+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:12:09.701+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2025-10-24T01:12:09.717+0000] {logging_mixin.py:137} INFO - [2025-10-24T01:12:09.717+0000] {dag.py:3441} INFO - Setting next_dagrun for data_pipeline_dag to 2025-10-24T00:00:00+00:00, run_after=2025-10-25T00:00:00+00:00
[2025-10-24T01:12:09.726+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/data_pipeline_dag.py took 0.496 seconds
